name: appengine
version: 0.4.2
author: Dart Team <misc@dartlang.org>
description: Support for using Dart as a custom runtime on Google App Engine Flexible Environment
homepage: https://github.com/dart-lang/appengine
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
  fixnum: '>=0.9.0 <0.11.0'
  gcloud: '>=0.4.0 <0.5.0'
  googleapis_auth: '>=0.2.3+6 <0.3.0'
  http: '^0.11.3+9'
  http_server: '^0.9.2'
  http2: '^0.1.1+2'
  logging: '>=0.9.3 <0.12.0'
  memcache: '^0.2.1+1'
  path: '^1.2.0'
  protobuf: '^0.5.0'
dev_dependencies:
  test: '^0.12.18+1'
