name: csslib
version: 0.14.1
author: Dart Team <misc@dartlang.org>
description: A library for parsing CSS.
homepage: https://github.com/dart-lang/csslib
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  args: '>=0.12.1 <2.0.0'
  logging: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  source_span: '>=1.4.0 <2.0.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  test: '>=0.12.0 <0.13.0'
