name: term_glyph
version: 1.0.0
description: Useful glyphs and Windows-safe equivalents.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/term_glyph

environment:
  sdk: '>=1.8.0 <2.0.0'

dev_dependencies:
  csv: '^3.0.0'
  dart_style: '^0.2.0'
  test: '^0.12.0'
