name: package_resolver
version: 1.0.2
description: First-class package resolution strategy classes.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/package_resolver

environment:
  sdk: '>=1.14.0 <2.0.0'

dependencies:
  collection: '^1.9.0'
  http: '^0.11.0'
  package_config: '>=0.1.0 <2.0.0'
  path: '^1.0.0'
dev_dependencies:
  shelf: '^0.6.0'
  test: '^0.12.0'
