name: pub_dev_image_proxy
environment:
  sdk: ^3.9.0-0

resolution: workspace

dependencies:
  shelf: ^1.4.2
  crypto: ^3.0.6
  http: ^1.5.0
  retry: ^3.1.2
  gcloud: ^0.8.19
  googleapis_auth: ^2.0.0
  googleapis: ^14.0.0
  yaml: ^3.1.3
  async: ^2.13.0
dev_dependencies:
  test:
  lints:
