# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: smoke_test
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="app"
      dart: 2.0.0-dev.65.0
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="app"
      dart: 2.0.0-dev.65.0
    - stage: smoke_test
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="pkg/_popularity"
      dart: 2.0.0-dev.65.0
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="pkg/_popularity"
      dart: 2.0.0-dev.65.0
    - stage: smoke_test
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="pkg/pub_dartdoc"
      dart: 2.0.0-dev.65.0
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="pkg/pub_dartdoc"
      dart: 2.0.0-dev.65.0

stages:
  - smoke_test
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
