---
# Configuration for the pub.dev staging site
canonicalPackagesBucketName: dartlang-pub-dev-canonical-packages
publicPackagesBucketName: dartlang-pub-dev-public-packages
incomingPackagesBucketName: dartlang-pub-dev-incoming-packages
projectId: dartlang-pub-dev
searchServicePrefix: https://search-dot-dartlang-pub-dev.appspot.com
defaultServiceBaseUrl: https://{{GAE_VERSION}}-dot-{{GOOGLE_CLOUD_PROJECT}}.appspot.com
dartdocStorageBucketName: dartlang-pub-dev--dartdoc-storage
popularityDumpBucketName: dartlang-pub-dev--popularity
searchSnapshotBucketName: dartlang-pub-dev--search-snapshot
maxTaskInstances: 50
maxTaskRunHours: 2
taskResultBucketName: dartlang-pub-dev-task-output
taskWorkerImage: us-central1-docker.pkg.dev/dartlang-pub-tasks/{{GOOGLE_CLOUD_PROJECT}}-worker-images/task-worker:{{GAE_VERSION}}
taskWorkerProject: dartlang-pub-tasks
taskWorkerNetwork: pub-workers
cosImage: projects/cos-cloud/global/images/family/cos-97-lts
taskWorkerServiceAccount: task-worker-dev@dartlang-pub-tasks.iam.gserviceaccount.com
imageBucketName: dartlang-pub-dev--pub-images
storageBaseUrl: https://storage.googleapis.com
pubClientAudience: 818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com
pubSiteAudience: 621485135717-idb8t8nnguphtu2drfn2u4ig7r56rm6n.apps.googleusercontent.com
pubServerAudience: 621485135717-082tj8o9vu32lbmquftsolqngk2o13lp.apps.googleusercontent.com
externalServiceAudience: https://pub.dev
gmailRelayServiceAccount:
gmailRelayImpersonatedGSuiteUser:
uploadSignerServiceAccount: package-uploader-signer@dartlang-pub-dev.iam.gserviceaccount.com
blockRobots: true
productionHosts:
- dartlang-pub-dev.appspot.com
- '{{GAE_SERVICE}}-dot-dartlang-pub-dev.appspot.com'
primaryApiUri: https://dartlang-pub-dev.appspot.com
primarySiteUri: https://{{GAE_VERSION}}-dot-dartlang-pub-dev.appspot.com
admins:
- oauthUserId: '111042304059633250784'
  email: istvan.soos@gmail.com
  permissions:
  - executeTool
  - listUsers
  - manageAssignedTags
  - managePackageOwnership
  - manageRetraction
  - removePackage
  - removeUsers
- oauthUserId: '109830288482976007810'
  email: pub-moderation-admin@dartlang-pub-dev.iam.gserviceaccount.com
  permissions:
  - executeTool
  - listUsers
  - manageAssignedTags
  - managePackageOwnership
  - manageRetraction
  - removePackage
  - removeUsers
- oauthUserId: '117672289743137340098'
  email: assigned-tags-admin@dartlang-pub-dev.iam.gserviceaccount.com
  permissions:
  - manageAssignedTags
tools:
  # Needs to be in sync with Dockerfile, setup-dart.sh and setup-flutter.sh
  stableDartSdkPath: '/tool/stable/dart-sdk'
  stableFlutterSdkPath: '/tool/stable/flutter'
  previewDartSdkPath: '/tool/preview/dart-sdk'
  previewFlutterSdkPath: '/tool/preview/flutter'
  futureDartSdkPath: '/tool/preview/dart-sdk' # same as preview
  futureFlutterSdkPath: '/tool/future/flutter'
