name: package_config
version: 1.0.3
description: Support for working with Package Resolution config files.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/package_config

environment:
  sdk: '>=1.11.0 <2.0.0'

dependencies:
  charcode: ^1.1.0
  path: ^1.0.0

dev_dependencies:
  test: ^0.12.0
