name: pubserver
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: A package containing interfaces and code for talking to a pub package repository and making a pub package server.
homepage: https://www.dartlang.org

environment:
  sdk: '>=1.5.0 <2.0.0'

dependencies:
  logging: ">=0.9.3 <1.0.0"
  mime: ">=0.9.1 <0.10.0"
  pub_semver: ">=1.1.0 <1.2.0"
  shelf: ">=0.5.6 <0.6.0"
  yaml: ">=2.1.2 <3.0.0"

dev_dependencies:
  unittest: ">=0.11.4 <0.12.0"
