name: http_server
version: 0.9.6
author: Dart Team <misc@dartlang.org>
description: Library of HTTP server classes.
homepage: https://www.github.com/dart-lang/http_server
environment:
  sdk: '>=1.15.0 <2.0.0'
dependencies:
  mime: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
