name: code_transformers
version: 0.5.1+3
author: Dart Team <misc@dartlang.org>
description: Collection of utilities related to creating barback transformers.
homepage: https://github.com/dart-lang/code-transformers
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.28.0 <0.31.0'
  barback: '>=0.14.2 <0.16.0'
  cli_util: '>=0.0.1 <0.2.0'
  path: '>=0.9.0 <2.0.0'
  source_maps: '>=0.9.4 <0.11.0'
  source_span: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.1 <0.13.0'
  transformer_test: '>=0.1.0 <0.3.0'
