name: pub_integration
publish_to: none  # don't publish yet
description: Tools for integration tests.

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  _pub_shared:
  args: ^2.0.0
  http: ^1.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  puppeteer: 3.20.0
  puppeteer_screenshots:
  retry: ^3.1.2
  oauth2: ^2.0.0

dev_dependencies:
  coverage: any # test already depends on it
  pubspec_parse: ^1.5.0
  shelf: ^1.4.0
  test: ^1.16.5
