name: web_app
publish_to: none

environment:
  sdk: '^3.5.0'
resolution: workspace

dependencies:
  _pub_shared:
  api_builder:
  collection: ^1.18.0
  http: ^1.0.0
  intl: ^0.19.0
  markdown: ^7.2.0
  mdc_web: ^0.6.0
  meta: ^1.3.0
  web: ^1.0.0

dev_dependencies:
  test: ^1.16.5
