name: pub_dartdoc
author: Dart Team <misc@dartlang.org>
description: The customized dartdoc for pub.dartlang.org.
environment:
  sdk: ">=1.25.0-dev.9.0 <2.0.0"
dependencies:
  json_annotation: '^0.2.0'
  logging: '>=0.9.3 <1.0.0'
  meta: ^1.1.5
  path: ^1.6.0
  # dartdoc version to be pinned
  dartdoc: 0.20.0

dev_dependencies:
  build_runner: '^0.8.10'
  json_serializable: '^0.5.0'
  source_gen: '^0.8.0'
  test: ">=0.12.20 <0.13.0"
