language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.23.0
dart_task:
  - test: -p vm
  - test: -p firefox
  - test: -p dartium
    install_dartium: true
  - dartanalyzer
matrix:
  include:
    # Only validate formatting using the dev release
    # Formatted with 1.23.0+ which has (good) changes since 1.22.1
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
