name: _pub_shared
description: Shared data between the pub server and web_app client.
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  html: ^0.15.0
  json_annotation: ^4.3.0
  meta: ^1.3.0
  api_builder:
    path: ../api_builder

dev_dependencies:
  build_runner: '^2.0.0'
  build_verify: ^3.0.0
  coverage: any # test already depends on it
  json_serializable: ^6.0.1
  source_gen: '^1.0.0'
  test: '^1.16.5'
