name: _pub_shared
description: Shared data between the pub server and web_app client.
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  clock: ^1.1.0
  html: ^0.15.0
  json_annotation: ^4.3.0
  logging: ^1.2.0
  meta: ^1.3.0
  pub_semver: ^2.0.0
  sanitize_html: ^2.1.0
  api_builder:
    path: ../api_builder

dev_dependencies:
  build_runner: '^2.0.0'
  build_verify: ^3.0.0
  coverage: any # test already depends on it
  json_serializable: ^6.0.1
  source_gen: '^1.0.0'
  test: '^1.16.5'
