name: api_builder
description: Builder for generating API routers.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  build_config: ^1.0.0
  source_gen: ^1.0.0
  analyzer:  ^5.0.0
  shelf_router: ^1.0.0
  code_builder: ^4.0.0
  shelf: ^1.0.0
  meta: ^1.3.0
  http_methods: ^1.1.0
  http: ^0.13.0
  uuid: ^3.0.0
  logging: '>=0.11.3+2 <2.0.0'
dev_dependencies:
  test: ^1.16.5
  build_verify: ^3.0.0
  build_runner: ^2.0.0
