name: markdown
version: 0.8.0
author: Dart Team <misc@dartlang.org>
description: A library for converting markdown to HTML.
homepage: https://github.com/dart-lang/markdown
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  path: '^1.3.1'
  test: '^0.12.4+1'
