name: markdown
version: 0.7.2-dev
author: Dart Team <misc@dartlang.org>
description: A library for converting markdown to HTML.
homepage: https://github.com/dpeek/dart-markdown
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
