name: fake_gcloud
publish_to: none  # don't publish yet
description: Fake, in-memory implementation of `package:gcloud` interfaces.

environment:
  sdk: '^3.5.0'
resolution: workspace

dependencies:
  clock: ^1.1.0
  crypto: ^3.0.0
  gcloud: ^0.8.18
  logging: '>=0.11.3 <2.0.0'
  _discoveryapis_commons:

dev_dependencies:
  coverage: any # test already depends on it
  test: ^1.16.5
