name: gcloud
version: 0.1.3
author: Dart Team <misc@dartlang.org>
description: Dart gcloud APIs
homepage: https://github.com/dart-lang/gcloud
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  googleapis: '>=0.2.0 <0.6.0'
  googleapis_beta: '>=0.3.0 <0.6.0'
  http: '>=0.11.0 <0.12.0'
dev_dependencies:
  googleapis_auth: '>=0.1.1 <0.3.0'
  http_parser: '>=0.0.2+5 <0.1.0'
  mime: '>=0.9.0+3 <0.10.0'
  unittest: '>=0.11.0 <0.12.0'
transformers:
- $dart2js:
    $include: []
