name: fixnum
version: 0.10.6
author: Dart Team <misc@dartlang.org>
description: Library for 32- and 64-bit signed fixed-width integers.
homepage: https://github.com/dart-lang/fixnum
dev_dependencies:
  test: ^0.12.0
environment:
  sdk: ">=1.8.3 <2.0.0-dev.infinity"
