name: indexed_blob
publish_to: none
environment:
  sdk: '^3.5.0'
resolution: workspace

dependencies:
  async: ^2.8.0
  jsontool: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0
dev_dependencies:
  coverage: any # test already depends on it
  test: ^1.0.0
