name: pool
version: 1.3.3
author: Dart Team <misc@dartlang.org>
description: A class for managing a finite pool of resources.
homepage: https://github.com/dart-lang/pool
dependencies:
  async: ">=1.4.0 <3.0.0"
  stack_trace: ">=0.9.2 <2.0.0"
environment:
  sdk: ">=1.23.0 <2.0.0"
dev_dependencies:
  fake_async: ">=0.1.0 <0.2.0"
  test: ">=0.12.0 <0.13.0"
