name: code_coverage
publish_to: none  # don't publish yet
description: Code coverage tools.
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.0
  coverage: ^0.12.0
  lcov: ^5.3.0
  path: ^1.0.0

dev_dependencies:
  test: ^1.5.1
