name: code_coverage
publish_to: none  # don't publish yet
description: Code coverage tools.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.0.0
  coverage: ^1.3.2
  lcov: ^6.0.0
  path: ^1.8.0
  source_maps: ^0.10.10

dev_dependencies:
  test: ^1.16.5
