name: yaml
version: 2.1.13
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/yaml
description: A parser for YAML.
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  charcode: "^1.1.0"
  collection: ">=1.1.0 <2.0.0"
  string_scanner: ">=0.1.4 <2.0.0"
  source_span: ">=1.0.0 <2.0.0"
dev_dependencies:
  path: ">=1.2.0 <2.0.0"
  test: ">=0.12.0 <0.13.0"
