name: pana
description: Evaluate the health and quality of a Dart package
version: 0.5.1
homepage: https://github.com/dart-lang/pana
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  analyzer: ^0.30.0
  async: '>=1.13.3 <3.0.0'
  cli_util: ^0.1.1
  io: ^0.3.0
  json_annotation: ^0.2.0
  logging: ^0.11.3+1
  path: ^1.4.1
  pool: ^1.3.0
  pub_semver: ^1.3.2
  quiver: '>=0.24.0 <0.26.0'
  yaml: ^2.1.12

dev_dependencies:
  build: ^0.10.0
  build_runner: ^0.5.0
  json_serializable: ^0.2.4
  source_gen: ^0.7.2
  test: ^0.12.0
