name: source_maps
version: 0.10.4
author: Dart Team <misc@dartlang.org>
description: Library to programmatically manipulate source map files.
homepage: http://github.com/dart-lang/source_maps
dependencies:
  source_span: ^1.3.0
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
