name: pub_package_reader
description: Scans the package archive, extracts its main content and checks for errors.
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  logging: ^0.11.3
  meta: ^1.0.0
  pub_semver: ^1.4.4
  pubspec_parse: ^0.1.4
  yaml: ^2.0.0
  tar: 0.3.0

dev_dependencies:
  test: ^1.5.1
