name: pub_package_reader
description: Scans the package archive, extracts its main content and checks for errors.
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  logging: '>=0.11.3+1 <2.0.0'
  pub_semver: ^2.0.0
  pubspec_parse: '>=0.1.4 <2.0.0'
  yaml: ^3.0.0
  yaml_edit: ^2.0.1
  tar: 0.5.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  coverage: any # test already depends on it
  http: ^0.13.0
  test: ^1.16.5
